name: 'Comment on PR'

on:
  workflow_run:
    workflows: ["Pull Request Update"]
    types:
      - completed

jobs:
  comment:
    name: 'Post Comment on PR'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request_target' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download PR Variables
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: pr-variables

      - name: Restore Environment
        run: cat pr.env >> "${GITHUB_ENV}"

      - name: Add AppImage Links
        if: ${{ env.APPIMAGE }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: AppImage
          number: ${{ env.PR_NUMBER }}
          recreate: true
          message: |
            AppImages ready!
            <http://packages.viam.com/apps/slam-servers/carto_grpc_server-pr-${{ env.PR_NUMBER }}-aarch64.AppImage>
            <http://packages.viam.com/apps/slam-servers/carto_grpc_server-pr-${{ env.PR_NUMBER }}-x86_64.AppImage>

