name: Pull Request Update

concurrency: 
  group: pullrequest-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]
    types: [ 'opened', 'reopened', 'synchronize' ]

# To test workflow updates you need to work in a branch directly on viamrobotics/viam-cartographer
# and tag your working branch instead of @main in any viamrobotics/viam-cartographer "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: viamrobotics/viam-cartographer/.github/workflows/test.yml@main
  
  # This lets people add an "appimage" tag to have appimages built for the PR
  appimage:
    needs: [test]
    if: |
      always() && !cancelled() &&
      !contains(github.event.pull_request.labels.*.name, 'appimage-ignore-tests') &&
      contains(github.event.pull_request.labels.*.name, 'appimage') && needs.test.result == 'success'
    uses: viamrobotics/viam-cartographer/.github/workflows/appimage.yml@main
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  appimage-ignore-tests:
    if: |
       always() && !cancelled() && contains(github.event.pull_request.labels.*.name, 'appimage-ignore-tests')
    uses: viamrobotics/viam-cartographer/.github/workflows/appimage.yml@main
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
