name: Pull Request Update

concurrency: 
  group: pullrequest-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'kk/rsdk-2014-implement-cartographer-model' ]
    types: [ 'opened', 'reopened', 'synchronize' ]

# To test workflow updates you need to work in a branch directly on viamrobotics/viam-cartographer
# and tag your working branch instead of @main in any viamrobotics/viam-cartographer "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: viamrobotics/viam-cartographer/.github/workflows/test.yml@kk/rsdk-2014-implement-cartographer-model
