name: Pull Request Close

concurrency: 
  group: pullrequest-trusted-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches: [ 'qaworkflow' ]
    types: [ 'closed' ]

jobs:
  appimage_clean:
    name: Remove PR AppImages
    runs-on: ubuntu-latest

    steps:
    - name: Authorize GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Delete Files
      run: |
        gsutil rm "gs://packages.viam.com/apps/slam-server/carto_grpc_server-pr-${{ github.event.pull_request.number }}-*" || true
